In [1]:
import numpy as np
hoangtxt = np.loadtxt('./output_hoang.txt')
print(hoangtxt)
nghiatxt = np.loadtxt('./output_nghia.txt')
print(nghiatxt)
nhattxt = np.loadtxt('./output_nhat.txt')
print(nghiatxt)

[[1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 [1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 [1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 ...
 [1.098e+03 1.098e+03 1.098e+03 ... 9.340e+02 9.340e+02 9.340e+02]
 [1.098e+03 1.098e+03 1.098e+03 ... 9.340e+02 9.340e+02 9.340e+02]
 [1.098e+03 1.098e+03 1.098e+03 ... 9.340e+02 9.340e+02 9.340e+02]]
[[1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 [1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 [1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 ...
 [1.098e+03 1.098e+03 1.098e+03 ... 9.340e+02 9.340e+02 9.340e+02]
 [1.098e+03 1.098e+03 1.098e+03 ... 9.340e+02 9.340e+02 9.340e+02]
 [1.098e+03 1.098e+03 1.098e+03 ... 9.340e+02 9.340e+02 9.340e+02]]
[[1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 [1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.137e+03 4.137e+03]
 [1.000e+00 1.000e+00 1.000e+00 ... 4.137e+03 4.13

In [2]:
TF: np.ndarray = hoangtxt == nhattxt
print('hoang - nhat', np.unique(TF, return_counts=True))
TF: np.ndarray = nghiatxt == nhattxt
print('nghia - nhat', np.unique(TF, return_counts=True))
TF: np.ndarray = nghiatxt == hoangtxt
print('nghia - hoang', np.unique(TF, return_counts=True))

hoang - nhat (array([ True]), array([1000000]))
nghia - nhat (array([ True]), array([1000000]))
nghia - hoang (array([ True]), array([1000000]))


In [3]:
number, count = np.unique(nghiatxt, return_counts=True)
print(count[0])
number, count = np.unique(hoangtxt, return_counts=True)
print(count[0])
number, count = np.unique(nhattxt, return_counts=True)
print(count[0])

9354
9354
9354


In [4]:
rows, cols = np.where(np.array(nhattxt == nghiatxt) == False)

In [5]:
for i in range(rows.size):
    print(f'{rows[i]} - {cols[i]}')
    # print(f'hoang - nghia: {hoangtxt[rows[i],cols[i]]} - {nghiatxt[rows[i],cols[i]]}')

In [6]:
nhattxt[0:10,385:390]

array([[4.134e+03, 4.134e+03, 4.134e+03, 0.000e+00, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00]])

In [7]:
nghiatxt[0:10,385:390]

array([[4.134e+03, 4.134e+03, 4.134e+03, 0.000e+00, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00],
       [4.134e+03, 4.134e+03, 4.134e+03, 4.134e+03, 3.000e+00]])